services:
  postgres:
    image: postgres:15
    container_name: innogram-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - innogram-network

  redis:
    image: redis:7-alpine
    container_name: innogram-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - innogram-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: innogram-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT_AMQP:-5672}:5672"
      - "${RABBITMQ_PORT_MGMT}:15672"
    networks:
      - innogram-network

volumes:
  postgres_data:
  redis_data:

networks:
  innogram-network:
    driver: bridge
